mutation createNewUser(
    $slug: String!
    $authUserId: String!
    $pictureUrl: String!
    $firstname: String!
) {
    user: createOneUser(
        data: {
            slug: $slug
            authUserId: $authUserId
            pictureUrl: $pictureUrl
            firstname: $firstname
            sections: {
                create: [{ slug: "section", name: "My first section" }]
            }
        }
    ) {
        ...UserBasic
    }
}
