query getSections($authUserId: String!) {
    sections(where: { owner: { authUserId: { equals: $authUserId } } }) {
        id
        isExpanded
        title: name
        collections(where: { isDeleted: { equals: false } }) {
            id
            slug
            isDeleted
            title: name
        }
    }
}

mutation createSection {
    createEmptySection {
        id
        slug
        title: name
        index
    }
}

mutation updateSectionExpanded($isExpanded: Boolean!, $sectionId: ID!) {
    updateOneSection(
        where: { id: $sectionId }
        data: { isExpanded: $isExpanded }
    ) {
        id
        isExpanded
    }
}
