query getSections($authUserId: String!) {
    inbox {
        id
        count
    }
    sections(
        where: {
            isDeleted: { equals: false }
            owner: { authUserId: { equals: $authUserId } }
        }
    ) {
        id
        createdAt
        isExpanded
        title: name
        collections(
            where: { isDeleted: { equals: false } }
            orderBy: { createdAt: asc }
        ) {
            id
            slug
            isDeleted
            title: name
        }
    }
}

mutation createSection {
    createEmptySection {
        id
        slug
        createdAt
        title: name
        index
        isExpanded
        collections(where: { isDeleted: { equals: false } }) {
            id
            slug
            isDeleted
            title: name
        }
    }
}

mutation updateSectionExpanded($isExpanded: Boolean!, $sectionId: ID!) {
    updateOneSection(
        where: { id: $sectionId }
        data: { isExpanded: $isExpanded }
    ) {
        id
        isExpanded
    }
}
