query getProfile($slug: String) {
    user(where: { slug: $slug }) {
        ...UserBasic
        ...Social
    }
    sections(
        where: {
            owner: { slug: { equals: $slug } }
            isDeleted: { equals: false }
        }
    ) {
        id
        slug
        name
        index
    }
}

query getBreadcrumbs {
    breadcrumbs @client {
        title
        as
        href
    }
}
