query getCollectionModal($authUserId: String!) {
    collections(
        where: {
            isDeleted: { equals: false }
            owner: { authUserId: { equals: $authUserId } }
        }
    ) {
        id
        title: name
    }
}

query getStatusMessage {
    statusMessage @client
}
