/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as Context from './context'
import * as photon from '@prisma/photon'

declare global {
    interface NexusGenCustomOutputProperties<TypeName extends string> {
        crud: NexusPrisma<TypeName, 'crud'>
        model: NexusPrisma<TypeName, 'model'>
    }
}

declare global {
    interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
    BooleanFilter: {
        // input type
        equals?: boolean | null // Boolean
        not?: boolean | null // Boolean
    }
    CollectionCreateManyWithoutCollectionsInput: {
        // input type
        connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        create?: NexusGenInputs['CollectionCreateWithoutSectionInput'][] | null // [CollectionCreateWithoutSectionInput!]
    }
    CollectionCreateOneWithoutCollectionInput: {
        // input type
        connect?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
        create?: NexusGenInputs['CollectionCreateWithoutItemsInput'] | null // CollectionCreateWithoutItemsInput
    }
    CollectionCreateWithoutItemsInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        name?: string | null // String
        owner: NexusGenInputs['UserCreateOneWithoutOwnerInput'] // UserCreateOneWithoutOwnerInput!
        section: NexusGenInputs['SectionCreateOneWithoutSectionInput'] // SectionCreateOneWithoutSectionInput!
        slug: string // String!
        updatedAt?: any | null // DateTime
    }
    CollectionCreateWithoutOwnerInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        items?: NexusGenInputs['ItemCreateManyWithoutItemsInput'] | null // ItemCreateManyWithoutItemsInput
        name?: string | null // String
        section: NexusGenInputs['SectionCreateOneWithoutSectionInput'] // SectionCreateOneWithoutSectionInput!
        slug: string // String!
        updatedAt?: any | null // DateTime
    }
    CollectionCreateWithoutSectionInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        items?: NexusGenInputs['ItemCreateManyWithoutItemsInput'] | null // ItemCreateManyWithoutItemsInput
        name?: string | null // String
        owner: NexusGenInputs['UserCreateOneWithoutOwnerInput'] // UserCreateOneWithoutOwnerInput!
        slug: string // String!
        updatedAt?: any | null // DateTime
    }
    CollectionFilter: {
        // input type
        every?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
        none?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
        some?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
    }
    CollectionItemsOrderByInput: {
        // input type
        createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
        position?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    }
    CollectionItemsWhereInput: {
        // input type
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    }
    CollectionScalarWhereInput: {
        // input type
        AND?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        detail?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        items?: NexusGenInputs['ItemFilter'] | null // ItemFilter
        name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
        OR?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
        slug?: NexusGenInputs['StringFilter'] | null // StringFilter
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    }
    CollectionUpdateInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        items?: NexusGenInputs['ItemUpdateManyWithoutCollectionInput'] | null // ItemUpdateManyWithoutCollectionInput
        name?: string | null // String
        owner?:
            | NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
            | null // UserUpdateOneRequiredWithoutCollectionsInput
        section?:
            | NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
            | null // SectionUpdateOneRequiredWithoutCollectionsInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    CollectionUpdateManyDataInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        name?: string | null // String
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    CollectionUpdateManyWithWhereNestedInput: {
        // input type
        data: NexusGenInputs['CollectionUpdateManyDataInput'] // CollectionUpdateManyDataInput!
        where: NexusGenInputs['CollectionScalarWhereInput'] // CollectionScalarWhereInput!
    }
    CollectionUpdateManyWithoutOwnerInput: {
        // input type
        connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        create?: NexusGenInputs['CollectionCreateWithoutOwnerInput'][] | null // [CollectionCreateWithoutOwnerInput!]
        delete?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        deleteMany?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
        disconnect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        set?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        update?:
            | NexusGenInputs['CollectionUpdateWithWhereUniqueWithoutOwnerInput'][]
            | null // [CollectionUpdateWithWhereUniqueWithoutOwnerInput!]
        updateMany?:
            | NexusGenInputs['CollectionUpdateManyWithWhereNestedInput'][]
            | null // [CollectionUpdateManyWithWhereNestedInput!]
        upsert?:
            | NexusGenInputs['CollectionUpsertWithWhereUniqueWithoutOwnerInput'][]
            | null // [CollectionUpsertWithWhereUniqueWithoutOwnerInput!]
    }
    CollectionUpdateManyWithoutSectionInput: {
        // input type
        connect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        create?: NexusGenInputs['CollectionCreateWithoutSectionInput'][] | null // [CollectionCreateWithoutSectionInput!]
        delete?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        deleteMany?: NexusGenInputs['CollectionScalarWhereInput'][] | null // [CollectionScalarWhereInput!]
        disconnect?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        set?: NexusGenInputs['CollectionWhereUniqueInput'][] | null // [CollectionWhereUniqueInput!]
        update?:
            | NexusGenInputs['CollectionUpdateWithWhereUniqueWithoutSectionInput'][]
            | null // [CollectionUpdateWithWhereUniqueWithoutSectionInput!]
        updateMany?:
            | NexusGenInputs['CollectionUpdateManyWithWhereNestedInput'][]
            | null // [CollectionUpdateManyWithWhereNestedInput!]
        upsert?:
            | NexusGenInputs['CollectionUpsertWithWhereUniqueWithoutSectionInput'][]
            | null // [CollectionUpsertWithWhereUniqueWithoutSectionInput!]
    }
    CollectionUpdateOneWithoutItemsInput: {
        // input type
        connect?: NexusGenInputs['CollectionWhereUniqueInput'] | null // CollectionWhereUniqueInput
        create?: NexusGenInputs['CollectionCreateWithoutItemsInput'] | null // CollectionCreateWithoutItemsInput
        delete?: boolean | null // Boolean
        disconnect?: boolean | null // Boolean
        update?: NexusGenInputs['CollectionUpdateWithoutItemsDataInput'] | null // CollectionUpdateWithoutItemsDataInput
        upsert?: NexusGenInputs['CollectionUpsertWithoutItemsInput'] | null // CollectionUpsertWithoutItemsInput
    }
    CollectionUpdateWithWhereUniqueWithoutOwnerInput: {
        // input type
        data: NexusGenInputs['CollectionUpdateWithoutOwnerDataInput'] // CollectionUpdateWithoutOwnerDataInput!
        where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
    }
    CollectionUpdateWithWhereUniqueWithoutSectionInput: {
        // input type
        data: NexusGenInputs['CollectionUpdateWithoutSectionDataInput'] // CollectionUpdateWithoutSectionDataInput!
        where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
    }
    CollectionUpdateWithoutItemsDataInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        name?: string | null // String
        owner?:
            | NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
            | null // UserUpdateOneRequiredWithoutCollectionsInput
        section?:
            | NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
            | null // SectionUpdateOneRequiredWithoutCollectionsInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    CollectionUpdateWithoutOwnerDataInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        items?: NexusGenInputs['ItemUpdateManyWithoutCollectionInput'] | null // ItemUpdateManyWithoutCollectionInput
        name?: string | null // String
        section?:
            | NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
            | null // SectionUpdateOneRequiredWithoutCollectionsInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    CollectionUpdateWithoutSectionDataInput: {
        // input type
        createdAt?: any | null // DateTime
        detail?: string | null // String
        id?: string | null // ID
        isDeleted?: boolean | null // Boolean
        items?: NexusGenInputs['ItemUpdateManyWithoutCollectionInput'] | null // ItemUpdateManyWithoutCollectionInput
        name?: string | null // String
        owner?:
            | NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
            | null // UserUpdateOneRequiredWithoutCollectionsInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    CollectionUpsertWithWhereUniqueWithoutOwnerInput: {
        // input type
        create: NexusGenInputs['CollectionCreateWithoutOwnerInput'] // CollectionCreateWithoutOwnerInput!
        update: NexusGenInputs['CollectionUpdateWithoutOwnerDataInput'] // CollectionUpdateWithoutOwnerDataInput!
        where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
    }
    CollectionUpsertWithWhereUniqueWithoutSectionInput: {
        // input type
        create: NexusGenInputs['CollectionCreateWithoutSectionInput'] // CollectionCreateWithoutSectionInput!
        update: NexusGenInputs['CollectionUpdateWithoutSectionDataInput'] // CollectionUpdateWithoutSectionDataInput!
        where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
    }
    CollectionUpsertWithoutItemsInput: {
        // input type
        create: NexusGenInputs['CollectionCreateWithoutItemsInput'] // CollectionCreateWithoutItemsInput!
        update: NexusGenInputs['CollectionUpdateWithoutItemsDataInput'] // CollectionUpdateWithoutItemsDataInput!
    }
    CollectionWhereInput: {
        // input type
        AND?: NexusGenInputs['CollectionWhereInput'][] | null // [CollectionWhereInput!]
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        detail?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        items?: NexusGenInputs['ItemFilter'] | null // ItemFilter
        name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['CollectionWhereInput'][] | null // [CollectionWhereInput!]
        OR?: NexusGenInputs['CollectionWhereInput'][] | null // [CollectionWhereInput!]
        owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
        section?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
        slug?: NexusGenInputs['StringFilter'] | null // StringFilter
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    }
    CollectionWhereUniqueInput: {
        // input type
        id?: string | null // ID
        slug?: string | null // String
    }
    DateTimeFilter: {
        // input type
        equals?: any | null // DateTime
        gt?: any | null // DateTime
        gte?: any | null // DateTime
        in?: any[] | null // [DateTime!]
        lt?: any | null // DateTime
        lte?: any | null // DateTime
        not?: any | null // DateTime
        notIn?: any[] | null // [DateTime!]
    }
    IntFilter: {
        // input type
        equals?: number | null // Int
        gt?: number | null // Int
        gte?: number | null // Int
        in?: number[] | null // [Int!]
        lt?: number | null // Int
        lte?: number | null // Int
        not?: number | null // Int
        notIn?: number[] | null // [Int!]
    }
    ItemCreateManyWithoutInboxedItemsInput: {
        // input type
        connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        create?: NexusGenInputs['ItemCreateWithoutInboxOwnerInput'][] | null // [ItemCreateWithoutInboxOwnerInput!]
    }
    ItemCreateManyWithoutItemsInput: {
        // input type
        connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        create?: NexusGenInputs['ItemCreateWithoutCollectionInput'][] | null // [ItemCreateWithoutCollectionInput!]
    }
    ItemCreateWithoutCollectionInput: {
        // input type
        author?: string | null // String
        comment?: string | null // String
        createdAt?: any | null // DateTime
        description?: string | null // String
        id?: string | null // ID
        imageUrl?: string | null // String
        inboxOwner?:
            | NexusGenInputs['UserCreateOneWithoutInboxOwnerInput']
            | null // UserCreateOneWithoutInboxOwnerInput
        isDeleted?: boolean | null // Boolean
        meta?: string | null // String
        position?: number | null // Int
        productUrl?: string | null // String
        provider?: string | null // String
        title: string // String!
        type: NexusGenEnums['ItemType'] // ItemType!
        updatedAt?: any | null // DateTime
    }
    ItemCreateWithoutInboxOwnerInput: {
        // input type
        author?: string | null // String
        collection?:
            | NexusGenInputs['CollectionCreateOneWithoutCollectionInput']
            | null // CollectionCreateOneWithoutCollectionInput
        comment?: string | null // String
        createdAt?: any | null // DateTime
        description?: string | null // String
        id?: string | null // ID
        imageUrl?: string | null // String
        isDeleted?: boolean | null // Boolean
        meta?: string | null // String
        position?: number | null // Int
        productUrl?: string | null // String
        provider?: string | null // String
        title: string // String!
        type: NexusGenEnums['ItemType'] // ItemType!
        updatedAt?: any | null // DateTime
    }
    ItemFilter: {
        // input type
        every?: NexusGenInputs['ItemWhereInput'] | null // ItemWhereInput
        none?: NexusGenInputs['ItemWhereInput'] | null // ItemWhereInput
        some?: NexusGenInputs['ItemWhereInput'] | null // ItemWhereInput
    }
    ItemScalarWhereInput: {
        // input type
        AND?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
        author?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        comment?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        description?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        imageUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        meta?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
        OR?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
        position?: NexusGenInputs['IntFilter'] | null // IntFilter
        productUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        provider?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        title?: NexusGenInputs['StringFilter'] | null // StringFilter
        type?: NexusGenEnums['ItemType'] | null // ItemType
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    }
    ItemUpdateInput: {
        // input type
        author?: string | null // String
        collection?:
            | NexusGenInputs['CollectionUpdateOneWithoutItemsInput']
            | null // CollectionUpdateOneWithoutItemsInput
        comment?: string | null // String
        createdAt?: any | null // DateTime
        description?: string | null // String
        id?: string | null // ID
        imageUrl?: string | null // String
        inboxOwner?:
            | NexusGenInputs['UserUpdateOneWithoutInboxedItemsInput']
            | null // UserUpdateOneWithoutInboxedItemsInput
        isDeleted?: boolean | null // Boolean
        meta?: string | null // String
        position?: number | null // Int
        productUrl?: string | null // String
        provider?: string | null // String
        title?: string | null // String
        type?: NexusGenEnums['ItemType'] | null // ItemType
        updatedAt?: any | null // DateTime
    }
    ItemUpdateManyDataInput: {
        // input type
        author?: string | null // String
        comment?: string | null // String
        createdAt?: any | null // DateTime
        description?: string | null // String
        id?: string | null // ID
        imageUrl?: string | null // String
        isDeleted?: boolean | null // Boolean
        meta?: string | null // String
        position?: number | null // Int
        productUrl?: string | null // String
        provider?: string | null // String
        title?: string | null // String
        type?: NexusGenEnums['ItemType'] | null // ItemType
        updatedAt?: any | null // DateTime
    }
    ItemUpdateManyWithWhereNestedInput: {
        // input type
        data: NexusGenInputs['ItemUpdateManyDataInput'] // ItemUpdateManyDataInput!
        where: NexusGenInputs['ItemScalarWhereInput'] // ItemScalarWhereInput!
    }
    ItemUpdateManyWithoutCollectionInput: {
        // input type
        connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        create?: NexusGenInputs['ItemCreateWithoutCollectionInput'][] | null // [ItemCreateWithoutCollectionInput!]
        delete?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        deleteMany?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
        disconnect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        set?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        update?:
            | NexusGenInputs['ItemUpdateWithWhereUniqueWithoutCollectionInput'][]
            | null // [ItemUpdateWithWhereUniqueWithoutCollectionInput!]
        updateMany?:
            | NexusGenInputs['ItemUpdateManyWithWhereNestedInput'][]
            | null // [ItemUpdateManyWithWhereNestedInput!]
        upsert?:
            | NexusGenInputs['ItemUpsertWithWhereUniqueWithoutCollectionInput'][]
            | null // [ItemUpsertWithWhereUniqueWithoutCollectionInput!]
    }
    ItemUpdateManyWithoutInboxOwnerInput: {
        // input type
        connect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        create?: NexusGenInputs['ItemCreateWithoutInboxOwnerInput'][] | null // [ItemCreateWithoutInboxOwnerInput!]
        delete?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        deleteMany?: NexusGenInputs['ItemScalarWhereInput'][] | null // [ItemScalarWhereInput!]
        disconnect?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        set?: NexusGenInputs['ItemWhereUniqueInput'][] | null // [ItemWhereUniqueInput!]
        update?:
            | NexusGenInputs['ItemUpdateWithWhereUniqueWithoutInboxOwnerInput'][]
            | null // [ItemUpdateWithWhereUniqueWithoutInboxOwnerInput!]
        updateMany?:
            | NexusGenInputs['ItemUpdateManyWithWhereNestedInput'][]
            | null // [ItemUpdateManyWithWhereNestedInput!]
        upsert?:
            | NexusGenInputs['ItemUpsertWithWhereUniqueWithoutInboxOwnerInput'][]
            | null // [ItemUpsertWithWhereUniqueWithoutInboxOwnerInput!]
    }
    ItemUpdateWithWhereUniqueWithoutCollectionInput: {
        // input type
        data: NexusGenInputs['ItemUpdateWithoutCollectionDataInput'] // ItemUpdateWithoutCollectionDataInput!
        where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
    }
    ItemUpdateWithWhereUniqueWithoutInboxOwnerInput: {
        // input type
        data: NexusGenInputs['ItemUpdateWithoutInboxOwnerDataInput'] // ItemUpdateWithoutInboxOwnerDataInput!
        where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
    }
    ItemUpdateWithoutCollectionDataInput: {
        // input type
        author?: string | null // String
        comment?: string | null // String
        createdAt?: any | null // DateTime
        description?: string | null // String
        id?: string | null // ID
        imageUrl?: string | null // String
        inboxOwner?:
            | NexusGenInputs['UserUpdateOneWithoutInboxedItemsInput']
            | null // UserUpdateOneWithoutInboxedItemsInput
        isDeleted?: boolean | null // Boolean
        meta?: string | null // String
        position?: number | null // Int
        productUrl?: string | null // String
        provider?: string | null // String
        title?: string | null // String
        type?: NexusGenEnums['ItemType'] | null // ItemType
        updatedAt?: any | null // DateTime
    }
    ItemUpdateWithoutInboxOwnerDataInput: {
        // input type
        author?: string | null // String
        collection?:
            | NexusGenInputs['CollectionUpdateOneWithoutItemsInput']
            | null // CollectionUpdateOneWithoutItemsInput
        comment?: string | null // String
        createdAt?: any | null // DateTime
        description?: string | null // String
        id?: string | null // ID
        imageUrl?: string | null // String
        isDeleted?: boolean | null // Boolean
        meta?: string | null // String
        position?: number | null // Int
        productUrl?: string | null // String
        provider?: string | null // String
        title?: string | null // String
        type?: NexusGenEnums['ItemType'] | null // ItemType
        updatedAt?: any | null // DateTime
    }
    ItemUpsertWithWhereUniqueWithoutCollectionInput: {
        // input type
        create: NexusGenInputs['ItemCreateWithoutCollectionInput'] // ItemCreateWithoutCollectionInput!
        update: NexusGenInputs['ItemUpdateWithoutCollectionDataInput'] // ItemUpdateWithoutCollectionDataInput!
        where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
    }
    ItemUpsertWithWhereUniqueWithoutInboxOwnerInput: {
        // input type
        create: NexusGenInputs['ItemCreateWithoutInboxOwnerInput'] // ItemCreateWithoutInboxOwnerInput!
        update: NexusGenInputs['ItemUpdateWithoutInboxOwnerDataInput'] // ItemUpdateWithoutInboxOwnerDataInput!
        where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
    }
    ItemWhereInput: {
        // input type
        AND?: NexusGenInputs['ItemWhereInput'][] | null // [ItemWhereInput!]
        author?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        collection?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
        comment?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        description?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        imageUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        inboxOwner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        meta?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['ItemWhereInput'][] | null // [ItemWhereInput!]
        OR?: NexusGenInputs['ItemWhereInput'][] | null // [ItemWhereInput!]
        position?: NexusGenInputs['IntFilter'] | null // IntFilter
        productUrl?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        provider?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        title?: NexusGenInputs['StringFilter'] | null // StringFilter
        type?: NexusGenEnums['ItemType'] | null // ItemType
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    }
    ItemWhereUniqueInput: {
        // input type
        id?: string | null // ID
    }
    NullableStringFilter: {
        // input type
        contains?: string | null // String
        endsWith?: string | null // String
        equals?: string | null // String
        gt?: string | null // String
        gte?: string | null // String
        in?: string[] | null // [String!]
        lt?: string | null // String
        lte?: string | null // String
        not?: string | null // String
        notIn?: string[] | null // [String!]
        startsWith?: string | null // String
    }
    QueryCollectionsOrderByInput: {
        // input type
        createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    }
    QueryCollectionsWhereInput: {
        // input type
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
        section?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
    }
    QueryItemsOrderByInput: {
        // input type
        position?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    }
    QueryItemsWhereInput: {
        // input type
        collection?: NexusGenInputs['CollectionWhereInput'] | null // CollectionWhereInput
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    }
    QuerySectionsOrderByInput: {
        // input type
        createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    }
    QuerySectionsWhereInput: {
        // input type
        index?: NexusGenInputs['IntFilter'] | null // IntFilter
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
    }
    SectionCollectionsOrderByInput: {
        // input type
        createdAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
        updatedAt?: NexusGenEnums['OrderByArg'] | null // OrderByArg
    }
    SectionCollectionsWhereInput: {
        // input type
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
    }
    SectionCreateManyWithoutSectionsInput: {
        // input type
        connect?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
        create?: NexusGenInputs['SectionCreateWithoutOwnerInput'][] | null // [SectionCreateWithoutOwnerInput!]
    }
    SectionCreateOneWithoutSectionInput: {
        // input type
        connect?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
        create?: NexusGenInputs['SectionCreateWithoutCollectionsInput'] | null // SectionCreateWithoutCollectionsInput
    }
    SectionCreateWithoutCollectionsInput: {
        // input type
        createdAt?: any | null // DateTime
        id?: string | null // ID
        index?: number | null // Int
        isDeleted?: boolean | null // Boolean
        isExpanded?: boolean | null // Boolean
        name?: string | null // String
        owner: NexusGenInputs['UserCreateOneWithoutOwnerInput'] // UserCreateOneWithoutOwnerInput!
        slug: string // String!
        updatedAt?: any | null // DateTime
    }
    SectionCreateWithoutOwnerInput: {
        // input type
        collections?:
            | NexusGenInputs['CollectionCreateManyWithoutCollectionsInput']
            | null // CollectionCreateManyWithoutCollectionsInput
        createdAt?: any | null // DateTime
        id?: string | null // ID
        index?: number | null // Int
        isDeleted?: boolean | null // Boolean
        isExpanded?: boolean | null // Boolean
        name?: string | null // String
        slug: string // String!
        updatedAt?: any | null // DateTime
    }
    SectionFilter: {
        // input type
        every?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
        none?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
        some?: NexusGenInputs['SectionWhereInput'] | null // SectionWhereInput
    }
    SectionScalarWhereInput: {
        // input type
        AND?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
        collections?: NexusGenInputs['CollectionFilter'] | null // CollectionFilter
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        index?: NexusGenInputs['IntFilter'] | null // IntFilter
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        isExpanded?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
        OR?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
        slug?: NexusGenInputs['StringFilter'] | null // StringFilter
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    }
    SectionUpdateInput: {
        // input type
        collections?:
            | NexusGenInputs['CollectionUpdateManyWithoutSectionInput']
            | null // CollectionUpdateManyWithoutSectionInput
        createdAt?: any | null // DateTime
        id?: string | null // ID
        index?: number | null // Int
        isDeleted?: boolean | null // Boolean
        isExpanded?: boolean | null // Boolean
        name?: string | null // String
        owner?:
            | NexusGenInputs['UserUpdateOneRequiredWithoutSectionsInput']
            | null // UserUpdateOneRequiredWithoutSectionsInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    SectionUpdateManyDataInput: {
        // input type
        createdAt?: any | null // DateTime
        id?: string | null // ID
        index?: number | null // Int
        isDeleted?: boolean | null // Boolean
        isExpanded?: boolean | null // Boolean
        name?: string | null // String
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    SectionUpdateManyWithWhereNestedInput: {
        // input type
        data: NexusGenInputs['SectionUpdateManyDataInput'] // SectionUpdateManyDataInput!
        where: NexusGenInputs['SectionScalarWhereInput'] // SectionScalarWhereInput!
    }
    SectionUpdateManyWithoutOwnerInput: {
        // input type
        connect?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
        create?: NexusGenInputs['SectionCreateWithoutOwnerInput'][] | null // [SectionCreateWithoutOwnerInput!]
        delete?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
        deleteMany?: NexusGenInputs['SectionScalarWhereInput'][] | null // [SectionScalarWhereInput!]
        disconnect?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
        set?: NexusGenInputs['SectionWhereUniqueInput'][] | null // [SectionWhereUniqueInput!]
        update?:
            | NexusGenInputs['SectionUpdateWithWhereUniqueWithoutOwnerInput'][]
            | null // [SectionUpdateWithWhereUniqueWithoutOwnerInput!]
        updateMany?:
            | NexusGenInputs['SectionUpdateManyWithWhereNestedInput'][]
            | null // [SectionUpdateManyWithWhereNestedInput!]
        upsert?:
            | NexusGenInputs['SectionUpsertWithWhereUniqueWithoutOwnerInput'][]
            | null // [SectionUpsertWithWhereUniqueWithoutOwnerInput!]
    }
    SectionUpdateOneRequiredWithoutCollectionsInput: {
        // input type
        connect?: NexusGenInputs['SectionWhereUniqueInput'] | null // SectionWhereUniqueInput
        create?: NexusGenInputs['SectionCreateWithoutCollectionsInput'] | null // SectionCreateWithoutCollectionsInput
        update?:
            | NexusGenInputs['SectionUpdateWithoutCollectionsDataInput']
            | null // SectionUpdateWithoutCollectionsDataInput
        upsert?: NexusGenInputs['SectionUpsertWithoutCollectionsInput'] | null // SectionUpsertWithoutCollectionsInput
    }
    SectionUpdateWithWhereUniqueWithoutOwnerInput: {
        // input type
        data: NexusGenInputs['SectionUpdateWithoutOwnerDataInput'] // SectionUpdateWithoutOwnerDataInput!
        where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
    }
    SectionUpdateWithoutCollectionsDataInput: {
        // input type
        createdAt?: any | null // DateTime
        id?: string | null // ID
        index?: number | null // Int
        isDeleted?: boolean | null // Boolean
        isExpanded?: boolean | null // Boolean
        name?: string | null // String
        owner?:
            | NexusGenInputs['UserUpdateOneRequiredWithoutSectionsInput']
            | null // UserUpdateOneRequiredWithoutSectionsInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    SectionUpdateWithoutOwnerDataInput: {
        // input type
        collections?:
            | NexusGenInputs['CollectionUpdateManyWithoutSectionInput']
            | null // CollectionUpdateManyWithoutSectionInput
        createdAt?: any | null // DateTime
        id?: string | null // ID
        index?: number | null // Int
        isDeleted?: boolean | null // Boolean
        isExpanded?: boolean | null // Boolean
        name?: string | null // String
        slug?: string | null // String
        updatedAt?: any | null // DateTime
    }
    SectionUpsertWithWhereUniqueWithoutOwnerInput: {
        // input type
        create: NexusGenInputs['SectionCreateWithoutOwnerInput'] // SectionCreateWithoutOwnerInput!
        update: NexusGenInputs['SectionUpdateWithoutOwnerDataInput'] // SectionUpdateWithoutOwnerDataInput!
        where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
    }
    SectionUpsertWithoutCollectionsInput: {
        // input type
        create: NexusGenInputs['SectionCreateWithoutCollectionsInput'] // SectionCreateWithoutCollectionsInput!
        update: NexusGenInputs['SectionUpdateWithoutCollectionsDataInput'] // SectionUpdateWithoutCollectionsDataInput!
    }
    SectionWhereInput: {
        // input type
        AND?: NexusGenInputs['SectionWhereInput'][] | null // [SectionWhereInput!]
        collections?: NexusGenInputs['CollectionFilter'] | null // CollectionFilter
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        index?: NexusGenInputs['IntFilter'] | null // IntFilter
        isDeleted?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        isExpanded?: NexusGenInputs['BooleanFilter'] | null // BooleanFilter
        name?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['SectionWhereInput'][] | null // [SectionWhereInput!]
        OR?: NexusGenInputs['SectionWhereInput'][] | null // [SectionWhereInput!]
        owner?: NexusGenInputs['UserWhereInput'] | null // UserWhereInput
        slug?: NexusGenInputs['StringFilter'] | null // StringFilter
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
    }
    SectionWhereUniqueInput: {
        // input type
        id?: string | null // ID
    }
    StringFilter: {
        // input type
        contains?: string | null // String
        endsWith?: string | null // String
        equals?: string | null // String
        gt?: string | null // String
        gte?: string | null // String
        in?: string[] | null // [String!]
        lt?: string | null // String
        lte?: string | null // String
        not?: string | null // String
        notIn?: string[] | null // [String!]
        startsWith?: string | null // String
    }
    UserCreateInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        collections?:
            | NexusGenInputs['CollectionCreateManyWithoutCollectionsInput']
            | null // CollectionCreateManyWithoutCollectionsInput
        createdAt?: any | null // DateTime
        firstname: string // String!
        github?: string | null // String
        id?: string | null // ID
        inboxedItems?:
            | NexusGenInputs['ItemCreateManyWithoutInboxedItemsInput']
            | null // ItemCreateManyWithoutInboxedItemsInput
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl: string // String!
        sections?:
            | NexusGenInputs['SectionCreateManyWithoutSectionsInput']
            | null // SectionCreateManyWithoutSectionsInput
        slug: string // String!
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserCreateOneWithoutInboxOwnerInput: {
        // input type
        connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
        create?: NexusGenInputs['UserCreateWithoutInboxedItemsInput'] | null // UserCreateWithoutInboxedItemsInput
    }
    UserCreateOneWithoutOwnerInput: {
        // input type
        connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
        create?: NexusGenInputs['UserCreateWithoutCollectionsInput'] | null // UserCreateWithoutCollectionsInput
    }
    UserCreateWithoutCollectionsInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        createdAt?: any | null // DateTime
        firstname: string // String!
        github?: string | null // String
        id?: string | null // ID
        inboxedItems?:
            | NexusGenInputs['ItemCreateManyWithoutInboxedItemsInput']
            | null // ItemCreateManyWithoutInboxedItemsInput
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl: string // String!
        sections?:
            | NexusGenInputs['SectionCreateManyWithoutSectionsInput']
            | null // SectionCreateManyWithoutSectionsInput
        slug: string // String!
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserCreateWithoutInboxedItemsInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        collections?:
            | NexusGenInputs['CollectionCreateManyWithoutCollectionsInput']
            | null // CollectionCreateManyWithoutCollectionsInput
        createdAt?: any | null // DateTime
        firstname: string // String!
        github?: string | null // String
        id?: string | null // ID
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl: string // String!
        sections?:
            | NexusGenInputs['SectionCreateManyWithoutSectionsInput']
            | null // SectionCreateManyWithoutSectionsInput
        slug: string // String!
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserCreateWithoutSectionsInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        collections?:
            | NexusGenInputs['CollectionCreateManyWithoutCollectionsInput']
            | null // CollectionCreateManyWithoutCollectionsInput
        createdAt?: any | null // DateTime
        firstname: string // String!
        github?: string | null // String
        id?: string | null // ID
        inboxedItems?:
            | NexusGenInputs['ItemCreateManyWithoutInboxedItemsInput']
            | null // ItemCreateManyWithoutInboxedItemsInput
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl: string // String!
        slug: string // String!
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserUpdateInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        collections?:
            | NexusGenInputs['CollectionUpdateManyWithoutOwnerInput']
            | null // CollectionUpdateManyWithoutOwnerInput
        createdAt?: any | null // DateTime
        firstname?: string | null // String
        github?: string | null // String
        id?: string | null // ID
        inboxedItems?:
            | NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput']
            | null // ItemUpdateManyWithoutInboxOwnerInput
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl?: string | null // String
        sections?: NexusGenInputs['SectionUpdateManyWithoutOwnerInput'] | null // SectionUpdateManyWithoutOwnerInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserUpdateOneRequiredWithoutCollectionsInput: {
        // input type
        connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
        create?: NexusGenInputs['UserCreateWithoutCollectionsInput'] | null // UserCreateWithoutCollectionsInput
        update?: NexusGenInputs['UserUpdateWithoutCollectionsDataInput'] | null // UserUpdateWithoutCollectionsDataInput
        upsert?: NexusGenInputs['UserUpsertWithoutCollectionsInput'] | null // UserUpsertWithoutCollectionsInput
    }
    UserUpdateOneRequiredWithoutSectionsInput: {
        // input type
        connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
        create?: NexusGenInputs['UserCreateWithoutSectionsInput'] | null // UserCreateWithoutSectionsInput
        update?: NexusGenInputs['UserUpdateWithoutSectionsDataInput'] | null // UserUpdateWithoutSectionsDataInput
        upsert?: NexusGenInputs['UserUpsertWithoutSectionsInput'] | null // UserUpsertWithoutSectionsInput
    }
    UserUpdateOneWithoutInboxedItemsInput: {
        // input type
        connect?: NexusGenInputs['UserWhereUniqueInput'] | null // UserWhereUniqueInput
        create?: NexusGenInputs['UserCreateWithoutInboxedItemsInput'] | null // UserCreateWithoutInboxedItemsInput
        delete?: boolean | null // Boolean
        disconnect?: boolean | null // Boolean
        update?: NexusGenInputs['UserUpdateWithoutInboxedItemsDataInput'] | null // UserUpdateWithoutInboxedItemsDataInput
        upsert?: NexusGenInputs['UserUpsertWithoutInboxedItemsInput'] | null // UserUpsertWithoutInboxedItemsInput
    }
    UserUpdateWithoutCollectionsDataInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        createdAt?: any | null // DateTime
        firstname?: string | null // String
        github?: string | null // String
        id?: string | null // ID
        inboxedItems?:
            | NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput']
            | null // ItemUpdateManyWithoutInboxOwnerInput
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl?: string | null // String
        sections?: NexusGenInputs['SectionUpdateManyWithoutOwnerInput'] | null // SectionUpdateManyWithoutOwnerInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserUpdateWithoutInboxedItemsDataInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        collections?:
            | NexusGenInputs['CollectionUpdateManyWithoutOwnerInput']
            | null // CollectionUpdateManyWithoutOwnerInput
        createdAt?: any | null // DateTime
        firstname?: string | null // String
        github?: string | null // String
        id?: string | null // ID
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl?: string | null // String
        sections?: NexusGenInputs['SectionUpdateManyWithoutOwnerInput'] | null // SectionUpdateManyWithoutOwnerInput
        slug?: string | null // String
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserUpdateWithoutSectionsDataInput: {
        // input type
        authUserId?: string | null // String
        biography?: string | null // String
        collections?:
            | NexusGenInputs['CollectionUpdateManyWithoutOwnerInput']
            | null // CollectionUpdateManyWithoutOwnerInput
        createdAt?: any | null // DateTime
        firstname?: string | null // String
        github?: string | null // String
        id?: string | null // ID
        inboxedItems?:
            | NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput']
            | null // ItemUpdateManyWithoutInboxOwnerInput
        label?: string | null // String
        linkedin?: string | null // String
        mail?: string | null // String
        pictureUrl?: string | null // String
        slug?: string | null // String
        updatedAt?: any | null // DateTime
        website?: string | null // String
        youtube?: string | null // String
    }
    UserUpsertWithoutCollectionsInput: {
        // input type
        create: NexusGenInputs['UserCreateWithoutCollectionsInput'] // UserCreateWithoutCollectionsInput!
        update: NexusGenInputs['UserUpdateWithoutCollectionsDataInput'] // UserUpdateWithoutCollectionsDataInput!
    }
    UserUpsertWithoutInboxedItemsInput: {
        // input type
        create: NexusGenInputs['UserCreateWithoutInboxedItemsInput'] // UserCreateWithoutInboxedItemsInput!
        update: NexusGenInputs['UserUpdateWithoutInboxedItemsDataInput'] // UserUpdateWithoutInboxedItemsDataInput!
    }
    UserUpsertWithoutSectionsInput: {
        // input type
        create: NexusGenInputs['UserCreateWithoutSectionsInput'] // UserCreateWithoutSectionsInput!
        update: NexusGenInputs['UserUpdateWithoutSectionsDataInput'] // UserUpdateWithoutSectionsDataInput!
    }
    UserWhereInput: {
        // input type
        AND?: NexusGenInputs['UserWhereInput'][] | null // [UserWhereInput!]
        authUserId?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        biography?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        collections?: NexusGenInputs['CollectionFilter'] | null // CollectionFilter
        createdAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        firstname?: NexusGenInputs['StringFilter'] | null // StringFilter
        github?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        id?: NexusGenInputs['StringFilter'] | null // StringFilter
        inboxedItems?: NexusGenInputs['ItemFilter'] | null // ItemFilter
        label?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        linkedin?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        mail?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        NOT?: NexusGenInputs['UserWhereInput'][] | null // [UserWhereInput!]
        OR?: NexusGenInputs['UserWhereInput'][] | null // [UserWhereInput!]
        pictureUrl?: NexusGenInputs['StringFilter'] | null // StringFilter
        sections?: NexusGenInputs['SectionFilter'] | null // SectionFilter
        slug?: NexusGenInputs['StringFilter'] | null // StringFilter
        updatedAt?: NexusGenInputs['DateTimeFilter'] | null // DateTimeFilter
        website?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
        youtube?: NexusGenInputs['NullableStringFilter'] | null // NullableStringFilter
    }
    UserWhereUniqueInput: {
        // input type
        authUserId?: string | null // String
        id?: string | null // ID
        slug?: string | null // String
    }
}

export interface NexusGenEnums {
    ItemType: photon.ItemType
    OrderByArg: photon.OrderByArg
}

export interface NexusGenRootTypes {
    Collection: photon.Collection
    Inbox: {}
    Item: photon.Item
    Mutation: {}
    Query: {}
    SearchItem: {
        // root type
        author?: string | null // String
        id: string // String!
        title: string // String!
        type: string // String!
    }
    Section: photon.Section
    User: photon.User
    String: string
    Int: number
    Float: number
    Boolean: boolean
    ID: string
    DateTime: any
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
    BooleanFilter: NexusGenInputs['BooleanFilter']
    CollectionCreateManyWithoutCollectionsInput: NexusGenInputs['CollectionCreateManyWithoutCollectionsInput']
    CollectionCreateOneWithoutCollectionInput: NexusGenInputs['CollectionCreateOneWithoutCollectionInput']
    CollectionCreateWithoutItemsInput: NexusGenInputs['CollectionCreateWithoutItemsInput']
    CollectionCreateWithoutOwnerInput: NexusGenInputs['CollectionCreateWithoutOwnerInput']
    CollectionCreateWithoutSectionInput: NexusGenInputs['CollectionCreateWithoutSectionInput']
    CollectionFilter: NexusGenInputs['CollectionFilter']
    CollectionItemsOrderByInput: NexusGenInputs['CollectionItemsOrderByInput']
    CollectionItemsWhereInput: NexusGenInputs['CollectionItemsWhereInput']
    CollectionScalarWhereInput: NexusGenInputs['CollectionScalarWhereInput']
    CollectionUpdateInput: NexusGenInputs['CollectionUpdateInput']
    CollectionUpdateManyDataInput: NexusGenInputs['CollectionUpdateManyDataInput']
    CollectionUpdateManyWithWhereNestedInput: NexusGenInputs['CollectionUpdateManyWithWhereNestedInput']
    CollectionUpdateManyWithoutOwnerInput: NexusGenInputs['CollectionUpdateManyWithoutOwnerInput']
    CollectionUpdateManyWithoutSectionInput: NexusGenInputs['CollectionUpdateManyWithoutSectionInput']
    CollectionUpdateOneWithoutItemsInput: NexusGenInputs['CollectionUpdateOneWithoutItemsInput']
    CollectionUpdateWithWhereUniqueWithoutOwnerInput: NexusGenInputs['CollectionUpdateWithWhereUniqueWithoutOwnerInput']
    CollectionUpdateWithWhereUniqueWithoutSectionInput: NexusGenInputs['CollectionUpdateWithWhereUniqueWithoutSectionInput']
    CollectionUpdateWithoutItemsDataInput: NexusGenInputs['CollectionUpdateWithoutItemsDataInput']
    CollectionUpdateWithoutOwnerDataInput: NexusGenInputs['CollectionUpdateWithoutOwnerDataInput']
    CollectionUpdateWithoutSectionDataInput: NexusGenInputs['CollectionUpdateWithoutSectionDataInput']
    CollectionUpsertWithWhereUniqueWithoutOwnerInput: NexusGenInputs['CollectionUpsertWithWhereUniqueWithoutOwnerInput']
    CollectionUpsertWithWhereUniqueWithoutSectionInput: NexusGenInputs['CollectionUpsertWithWhereUniqueWithoutSectionInput']
    CollectionUpsertWithoutItemsInput: NexusGenInputs['CollectionUpsertWithoutItemsInput']
    CollectionWhereInput: NexusGenInputs['CollectionWhereInput']
    CollectionWhereUniqueInput: NexusGenInputs['CollectionWhereUniqueInput']
    DateTimeFilter: NexusGenInputs['DateTimeFilter']
    IntFilter: NexusGenInputs['IntFilter']
    ItemCreateManyWithoutInboxedItemsInput: NexusGenInputs['ItemCreateManyWithoutInboxedItemsInput']
    ItemCreateManyWithoutItemsInput: NexusGenInputs['ItemCreateManyWithoutItemsInput']
    ItemCreateWithoutCollectionInput: NexusGenInputs['ItemCreateWithoutCollectionInput']
    ItemCreateWithoutInboxOwnerInput: NexusGenInputs['ItemCreateWithoutInboxOwnerInput']
    ItemFilter: NexusGenInputs['ItemFilter']
    ItemScalarWhereInput: NexusGenInputs['ItemScalarWhereInput']
    ItemUpdateInput: NexusGenInputs['ItemUpdateInput']
    ItemUpdateManyDataInput: NexusGenInputs['ItemUpdateManyDataInput']
    ItemUpdateManyWithWhereNestedInput: NexusGenInputs['ItemUpdateManyWithWhereNestedInput']
    ItemUpdateManyWithoutCollectionInput: NexusGenInputs['ItemUpdateManyWithoutCollectionInput']
    ItemUpdateManyWithoutInboxOwnerInput: NexusGenInputs['ItemUpdateManyWithoutInboxOwnerInput']
    ItemUpdateWithWhereUniqueWithoutCollectionInput: NexusGenInputs['ItemUpdateWithWhereUniqueWithoutCollectionInput']
    ItemUpdateWithWhereUniqueWithoutInboxOwnerInput: NexusGenInputs['ItemUpdateWithWhereUniqueWithoutInboxOwnerInput']
    ItemUpdateWithoutCollectionDataInput: NexusGenInputs['ItemUpdateWithoutCollectionDataInput']
    ItemUpdateWithoutInboxOwnerDataInput: NexusGenInputs['ItemUpdateWithoutInboxOwnerDataInput']
    ItemUpsertWithWhereUniqueWithoutCollectionInput: NexusGenInputs['ItemUpsertWithWhereUniqueWithoutCollectionInput']
    ItemUpsertWithWhereUniqueWithoutInboxOwnerInput: NexusGenInputs['ItemUpsertWithWhereUniqueWithoutInboxOwnerInput']
    ItemWhereInput: NexusGenInputs['ItemWhereInput']
    ItemWhereUniqueInput: NexusGenInputs['ItemWhereUniqueInput']
    NullableStringFilter: NexusGenInputs['NullableStringFilter']
    QueryCollectionsOrderByInput: NexusGenInputs['QueryCollectionsOrderByInput']
    QueryCollectionsWhereInput: NexusGenInputs['QueryCollectionsWhereInput']
    QueryItemsOrderByInput: NexusGenInputs['QueryItemsOrderByInput']
    QueryItemsWhereInput: NexusGenInputs['QueryItemsWhereInput']
    QuerySectionsOrderByInput: NexusGenInputs['QuerySectionsOrderByInput']
    QuerySectionsWhereInput: NexusGenInputs['QuerySectionsWhereInput']
    SectionCollectionsOrderByInput: NexusGenInputs['SectionCollectionsOrderByInput']
    SectionCollectionsWhereInput: NexusGenInputs['SectionCollectionsWhereInput']
    SectionCreateManyWithoutSectionsInput: NexusGenInputs['SectionCreateManyWithoutSectionsInput']
    SectionCreateOneWithoutSectionInput: NexusGenInputs['SectionCreateOneWithoutSectionInput']
    SectionCreateWithoutCollectionsInput: NexusGenInputs['SectionCreateWithoutCollectionsInput']
    SectionCreateWithoutOwnerInput: NexusGenInputs['SectionCreateWithoutOwnerInput']
    SectionFilter: NexusGenInputs['SectionFilter']
    SectionScalarWhereInput: NexusGenInputs['SectionScalarWhereInput']
    SectionUpdateInput: NexusGenInputs['SectionUpdateInput']
    SectionUpdateManyDataInput: NexusGenInputs['SectionUpdateManyDataInput']
    SectionUpdateManyWithWhereNestedInput: NexusGenInputs['SectionUpdateManyWithWhereNestedInput']
    SectionUpdateManyWithoutOwnerInput: NexusGenInputs['SectionUpdateManyWithoutOwnerInput']
    SectionUpdateOneRequiredWithoutCollectionsInput: NexusGenInputs['SectionUpdateOneRequiredWithoutCollectionsInput']
    SectionUpdateWithWhereUniqueWithoutOwnerInput: NexusGenInputs['SectionUpdateWithWhereUniqueWithoutOwnerInput']
    SectionUpdateWithoutCollectionsDataInput: NexusGenInputs['SectionUpdateWithoutCollectionsDataInput']
    SectionUpdateWithoutOwnerDataInput: NexusGenInputs['SectionUpdateWithoutOwnerDataInput']
    SectionUpsertWithWhereUniqueWithoutOwnerInput: NexusGenInputs['SectionUpsertWithWhereUniqueWithoutOwnerInput']
    SectionUpsertWithoutCollectionsInput: NexusGenInputs['SectionUpsertWithoutCollectionsInput']
    SectionWhereInput: NexusGenInputs['SectionWhereInput']
    SectionWhereUniqueInput: NexusGenInputs['SectionWhereUniqueInput']
    StringFilter: NexusGenInputs['StringFilter']
    UserCreateInput: NexusGenInputs['UserCreateInput']
    UserCreateOneWithoutInboxOwnerInput: NexusGenInputs['UserCreateOneWithoutInboxOwnerInput']
    UserCreateOneWithoutOwnerInput: NexusGenInputs['UserCreateOneWithoutOwnerInput']
    UserCreateWithoutCollectionsInput: NexusGenInputs['UserCreateWithoutCollectionsInput']
    UserCreateWithoutInboxedItemsInput: NexusGenInputs['UserCreateWithoutInboxedItemsInput']
    UserCreateWithoutSectionsInput: NexusGenInputs['UserCreateWithoutSectionsInput']
    UserUpdateInput: NexusGenInputs['UserUpdateInput']
    UserUpdateOneRequiredWithoutCollectionsInput: NexusGenInputs['UserUpdateOneRequiredWithoutCollectionsInput']
    UserUpdateOneRequiredWithoutSectionsInput: NexusGenInputs['UserUpdateOneRequiredWithoutSectionsInput']
    UserUpdateOneWithoutInboxedItemsInput: NexusGenInputs['UserUpdateOneWithoutInboxedItemsInput']
    UserUpdateWithoutCollectionsDataInput: NexusGenInputs['UserUpdateWithoutCollectionsDataInput']
    UserUpdateWithoutInboxedItemsDataInput: NexusGenInputs['UserUpdateWithoutInboxedItemsDataInput']
    UserUpdateWithoutSectionsDataInput: NexusGenInputs['UserUpdateWithoutSectionsDataInput']
    UserUpsertWithoutCollectionsInput: NexusGenInputs['UserUpsertWithoutCollectionsInput']
    UserUpsertWithoutInboxedItemsInput: NexusGenInputs['UserUpsertWithoutInboxedItemsInput']
    UserUpsertWithoutSectionsInput: NexusGenInputs['UserUpsertWithoutSectionsInput']
    UserWhereInput: NexusGenInputs['UserWhereInput']
    UserWhereUniqueInput: NexusGenInputs['UserWhereUniqueInput']
    ItemType: NexusGenEnums['ItemType']
    OrderByArg: NexusGenEnums['OrderByArg']
}

export interface NexusGenFieldTypes {
    Collection: {
        // field return type
        createdAt: any // DateTime!
        detail: string | null // String
        id: string // ID!
        isDeleted: boolean // Boolean!
        items: NexusGenRootTypes['Item'][] // [Item!]!
        name: string | null // String
        owner: NexusGenRootTypes['User'] // User!
        section: NexusGenRootTypes['Section'] // Section!
        slug: string // String!
        updatedAt: any // DateTime!
    }
    Inbox: {
        // field return type
        count: number // Int!
        id: string // String!
        items: NexusGenRootTypes['Item'][] // [Item!]!
    }
    Item: {
        // field return type
        author: string | null // String
        comment: string | null // String
        createdAt: any // DateTime!
        description: string | null // String
        id: string // ID!
        imageUrl: string | null // String
        isDeleted: boolean // Boolean!
        meta: string | null // String
        position: number // Int!
        productUrl: string | null // String
        provider: string | null // String
        title: string // String!
        type: NexusGenEnums['ItemType'] // ItemType!
    }
    Mutation: {
        // field return type
        changeItemPosition: NexusGenRootTypes['Item'][] // [Item!]!
        createEmptyCollection: NexusGenRootTypes['Collection'] // Collection!
        createEmptySection: NexusGenRootTypes['Section'] // Section!
        createItemFromSearch: NexusGenRootTypes['Item'] // Item!
        createItemFromUrl: NexusGenRootTypes['Item'] // Item!
        createNewUser: NexusGenRootTypes['User'] // User!
        createOneUser: NexusGenRootTypes['User'] // User!
        updateOneCollection: NexusGenRootTypes['Collection'] | null // Collection
        updateOneItem: NexusGenRootTypes['Item'] | null // Item
        updateOneSection: NexusGenRootTypes['Section'] | null // Section
        updateOneUser: NexusGenRootTypes['User'] | null // User
    }
    Query: {
        // field return type
        collection: NexusGenRootTypes['Collection'] | null // Collection
        collections: NexusGenRootTypes['Collection'][] // [Collection!]!
        inbox: NexusGenRootTypes['Inbox'] | null // Inbox
        items: NexusGenRootTypes['Item'][] // [Item!]!
        search: NexusGenRootTypes['SearchItem'][] // [SearchItem!]!
        section: NexusGenRootTypes['Section'] | null // Section
        sections: NexusGenRootTypes['Section'][] // [Section!]!
        user: NexusGenRootTypes['User'] | null // User
    }
    SearchItem: {
        // field return type
        author: string | null // String
        id: string // String!
        title: string // String!
        type: string // String!
    }
    Section: {
        // field return type
        collections: NexusGenRootTypes['Collection'][] // [Collection!]!
        createdAt: any // DateTime!
        id: string // ID!
        index: number // Int!
        isExpanded: boolean // Boolean!
        name: string | null // String
        slug: string // String!
    }
    User: {
        // field return type
        authUserId: string | null // String
        biography: string | null // String
        firstname: string // String!
        github: string | null // String
        id: string // ID!
        label: string | null // String
        linkedin: string | null // String
        mail: string | null // String
        pictureUrl: string // String!
        sections: NexusGenRootTypes['Section'][] // [Section!]!
        slug: string // String!
        website: string | null // String
        youtube: string | null // String
    }
}

export interface NexusGenArgTypes {
    Collection: {
        items: {
            // args
            after?: string | null // ID
            before?: string | null // ID
            first?: number | null // Int
            last?: number | null // Int
            orderBy?: NexusGenInputs['CollectionItemsOrderByInput'] | null // CollectionItemsOrderByInput
            skip?: number | null // Int
            where?: NexusGenInputs['CollectionItemsWhereInput'] | null // CollectionItemsWhereInput
        }
    }
    Mutation: {
        changeItemPosition: {
            // args
            collectionId: string // ID!
            newIndex: number // Int!
            oldIndex: number // Int!
        }
        createEmptyCollection: {
            // args
            sectionId: string // ID!
        }
        createItemFromSearch: {
            // args
            collectionId?: string | null // String
            id: string // String!
            inbox?: boolean | null // Boolean
            kind: string // String!
        }
        createItemFromUrl: {
            // args
            collectionId?: string | null // String
            inbox?: boolean | null // Boolean
            url: string // String!
        }
        createNewUser: {
            // args
            authUserId: string // String!
            firstname: string // String!
            pictureUrl: string // String!
            slug: string // String!
        }
        createOneUser: {
            // args
            data: NexusGenInputs['UserCreateInput'] // UserCreateInput!
        }
        updateOneCollection: {
            // args
            data: NexusGenInputs['CollectionUpdateInput'] // CollectionUpdateInput!
            where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
        }
        updateOneItem: {
            // args
            data: NexusGenInputs['ItemUpdateInput'] // ItemUpdateInput!
            where: NexusGenInputs['ItemWhereUniqueInput'] // ItemWhereUniqueInput!
        }
        updateOneSection: {
            // args
            data: NexusGenInputs['SectionUpdateInput'] // SectionUpdateInput!
            where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
        }
        updateOneUser: {
            // args
            data: NexusGenInputs['UserUpdateInput'] // UserUpdateInput!
            where: NexusGenInputs['UserWhereUniqueInput'] // UserWhereUniqueInput!
        }
    }
    Query: {
        collection: {
            // args
            where: NexusGenInputs['CollectionWhereUniqueInput'] // CollectionWhereUniqueInput!
        }
        collections: {
            // args
            after?: string | null // ID
            before?: string | null // ID
            first?: number | null // Int
            last?: number | null // Int
            orderBy?: NexusGenInputs['QueryCollectionsOrderByInput'] | null // QueryCollectionsOrderByInput
            skip?: number | null // Int
            where?: NexusGenInputs['QueryCollectionsWhereInput'] | null // QueryCollectionsWhereInput
        }
        items: {
            // args
            after?: string | null // ID
            before?: string | null // ID
            first?: number | null // Int
            last?: number | null // Int
            orderBy?: NexusGenInputs['QueryItemsOrderByInput'] | null // QueryItemsOrderByInput
            skip?: number | null // Int
            where?: NexusGenInputs['QueryItemsWhereInput'] | null // QueryItemsWhereInput
        }
        search: {
            // args
            kind: string // String!
            q: string // String!
        }
        section: {
            // args
            where: NexusGenInputs['SectionWhereUniqueInput'] // SectionWhereUniqueInput!
        }
        sections: {
            // args
            after?: string | null // ID
            before?: string | null // ID
            first?: number | null // Int
            last?: number | null // Int
            orderBy?: NexusGenInputs['QuerySectionsOrderByInput'] | null // QuerySectionsOrderByInput
            skip?: number | null // Int
            where?: NexusGenInputs['QuerySectionsWhereInput'] | null // QuerySectionsWhereInput
        }
        user: {
            // args
            where: NexusGenInputs['UserWhereUniqueInput'] // UserWhereUniqueInput!
        }
    }
    Section: {
        collections: {
            // args
            after?: string | null // ID
            before?: string | null // ID
            first?: number | null // Int
            last?: number | null // Int
            orderBy?: NexusGenInputs['SectionCollectionsOrderByInput'] | null // SectionCollectionsOrderByInput
            skip?: number | null // Int
            where?: NexusGenInputs['SectionCollectionsWhereInput'] | null // SectionCollectionsWhereInput
        }
    }
    User: {
        sections: {
            // args
            after?: string | null // ID
            before?: string | null // ID
            first?: number | null // Int
            last?: number | null // Int
            skip?: number | null // Int
        }
    }
}

export interface NexusGenAbstractResolveReturnTypes {}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames =
    | 'Collection'
    | 'Inbox'
    | 'Item'
    | 'Mutation'
    | 'Query'
    | 'SearchItem'
    | 'Section'
    | 'User'

export type NexusGenInputNames =
    | 'BooleanFilter'
    | 'CollectionCreateManyWithoutCollectionsInput'
    | 'CollectionCreateOneWithoutCollectionInput'
    | 'CollectionCreateWithoutItemsInput'
    | 'CollectionCreateWithoutOwnerInput'
    | 'CollectionCreateWithoutSectionInput'
    | 'CollectionFilter'
    | 'CollectionItemsOrderByInput'
    | 'CollectionItemsWhereInput'
    | 'CollectionScalarWhereInput'
    | 'CollectionUpdateInput'
    | 'CollectionUpdateManyDataInput'
    | 'CollectionUpdateManyWithWhereNestedInput'
    | 'CollectionUpdateManyWithoutOwnerInput'
    | 'CollectionUpdateManyWithoutSectionInput'
    | 'CollectionUpdateOneWithoutItemsInput'
    | 'CollectionUpdateWithWhereUniqueWithoutOwnerInput'
    | 'CollectionUpdateWithWhereUniqueWithoutSectionInput'
    | 'CollectionUpdateWithoutItemsDataInput'
    | 'CollectionUpdateWithoutOwnerDataInput'
    | 'CollectionUpdateWithoutSectionDataInput'
    | 'CollectionUpsertWithWhereUniqueWithoutOwnerInput'
    | 'CollectionUpsertWithWhereUniqueWithoutSectionInput'
    | 'CollectionUpsertWithoutItemsInput'
    | 'CollectionWhereInput'
    | 'CollectionWhereUniqueInput'
    | 'DateTimeFilter'
    | 'IntFilter'
    | 'ItemCreateManyWithoutInboxedItemsInput'
    | 'ItemCreateManyWithoutItemsInput'
    | 'ItemCreateWithoutCollectionInput'
    | 'ItemCreateWithoutInboxOwnerInput'
    | 'ItemFilter'
    | 'ItemScalarWhereInput'
    | 'ItemUpdateInput'
    | 'ItemUpdateManyDataInput'
    | 'ItemUpdateManyWithWhereNestedInput'
    | 'ItemUpdateManyWithoutCollectionInput'
    | 'ItemUpdateManyWithoutInboxOwnerInput'
    | 'ItemUpdateWithWhereUniqueWithoutCollectionInput'
    | 'ItemUpdateWithWhereUniqueWithoutInboxOwnerInput'
    | 'ItemUpdateWithoutCollectionDataInput'
    | 'ItemUpdateWithoutInboxOwnerDataInput'
    | 'ItemUpsertWithWhereUniqueWithoutCollectionInput'
    | 'ItemUpsertWithWhereUniqueWithoutInboxOwnerInput'
    | 'ItemWhereInput'
    | 'ItemWhereUniqueInput'
    | 'NullableStringFilter'
    | 'QueryCollectionsOrderByInput'
    | 'QueryCollectionsWhereInput'
    | 'QueryItemsOrderByInput'
    | 'QueryItemsWhereInput'
    | 'QuerySectionsOrderByInput'
    | 'QuerySectionsWhereInput'
    | 'SectionCollectionsOrderByInput'
    | 'SectionCollectionsWhereInput'
    | 'SectionCreateManyWithoutSectionsInput'
    | 'SectionCreateOneWithoutSectionInput'
    | 'SectionCreateWithoutCollectionsInput'
    | 'SectionCreateWithoutOwnerInput'
    | 'SectionFilter'
    | 'SectionScalarWhereInput'
    | 'SectionUpdateInput'
    | 'SectionUpdateManyDataInput'
    | 'SectionUpdateManyWithWhereNestedInput'
    | 'SectionUpdateManyWithoutOwnerInput'
    | 'SectionUpdateOneRequiredWithoutCollectionsInput'
    | 'SectionUpdateWithWhereUniqueWithoutOwnerInput'
    | 'SectionUpdateWithoutCollectionsDataInput'
    | 'SectionUpdateWithoutOwnerDataInput'
    | 'SectionUpsertWithWhereUniqueWithoutOwnerInput'
    | 'SectionUpsertWithoutCollectionsInput'
    | 'SectionWhereInput'
    | 'SectionWhereUniqueInput'
    | 'StringFilter'
    | 'UserCreateInput'
    | 'UserCreateOneWithoutInboxOwnerInput'
    | 'UserCreateOneWithoutOwnerInput'
    | 'UserCreateWithoutCollectionsInput'
    | 'UserCreateWithoutInboxedItemsInput'
    | 'UserCreateWithoutSectionsInput'
    | 'UserUpdateInput'
    | 'UserUpdateOneRequiredWithoutCollectionsInput'
    | 'UserUpdateOneRequiredWithoutSectionsInput'
    | 'UserUpdateOneWithoutInboxedItemsInput'
    | 'UserUpdateWithoutCollectionsDataInput'
    | 'UserUpdateWithoutInboxedItemsDataInput'
    | 'UserUpdateWithoutSectionsDataInput'
    | 'UserUpsertWithoutCollectionsInput'
    | 'UserUpsertWithoutInboxedItemsInput'
    | 'UserUpsertWithoutSectionsInput'
    | 'UserWhereInput'
    | 'UserWhereUniqueInput'

export type NexusGenEnumNames = 'ItemType' | 'OrderByArg'

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames =
    | 'Boolean'
    | 'DateTime'
    | 'Float'
    | 'ID'
    | 'Int'
    | 'String'

export type NexusGenUnionNames = never

export interface NexusGenTypes {
    context: Context.Context
    inputTypes: NexusGenInputs
    rootTypes: NexusGenRootTypes
    argTypes: NexusGenArgTypes
    fieldTypes: NexusGenFieldTypes
    allTypes: NexusGenAllTypes
    inheritedFields: NexusGenInheritedFields
    objectNames: NexusGenObjectNames
    inputNames: NexusGenInputNames
    enumNames: NexusGenEnumNames
    interfaceNames: NexusGenInterfaceNames
    scalarNames: NexusGenScalarNames
    unionNames: NexusGenUnionNames
    allInputTypes:
        | NexusGenTypes['inputNames']
        | NexusGenTypes['enumNames']
        | NexusGenTypes['scalarNames']
    allOutputTypes:
        | NexusGenTypes['objectNames']
        | NexusGenTypes['enumNames']
        | NexusGenTypes['unionNames']
        | NexusGenTypes['interfaceNames']
        | NexusGenTypes['scalarNames']
    allNamedTypes:
        | NexusGenTypes['allInputTypes']
        | NexusGenTypes['allOutputTypes']
    abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames']
    abstractResolveReturn: NexusGenAbstractResolveReturnTypes
}

declare global {
    interface NexusGenPluginTypeConfig<TypeName extends string> {}
    interface NexusGenPluginFieldConfig<
        TypeName extends string,
        FieldName extends string
    > {}
    interface NexusGenPluginSchemaConfig {}
}
