query getInbox {
    inbox {
        id
        items {
            ...ItemPreview
            ...ItemDetail
        }
    }
}

mutation moveItemFromInboxToCollection($itemId: ID!, $collectionId: ID!) {
    updateOneItem(
        data: {
            collection: { connect: { id: $collectionId } }
            inboxOwner: { disconnect: true }
        }
        where: { id: $itemId }
    ) {
        id
    }
}
