query getCollection(
    $profileSlug: String
    $sectionSlug: String
    $sectionIndex: Int
) {
    collections(
        where: {
            section: {
                AND: {
                    OR: [
                        { slug: { equals: $sectionSlug } }
                        { index: { equals: $sectionIndex } }
                    ]
                    owner: { slug: { equals: $profileSlug } }
                }
            }
        }
    ) {
        ...CollectionBasic
        createdAt
        items(first: 4, where: { isDeleted: { equals: false } }) {
            ...ItemPreview
        }
    }
}
