mutation CreateItemFromUrl(
    $url: String!
    $collectionId: String
    $inbox: Boolean
) {
    items: createItemFromUrl(
        collectionId: $collectionId
        url: $url
        inbox: $inbox
    ) {
        ...ItemPreview
        ...ItemDetail
    }
}

mutation CreateItemFromSearch(
    $id: String!
    $kind: String!
    $collectionId: String
    $inbox: Boolean
) {
    items: createItemFromSearch(
        collectionId: $collectionId
        id: $id
        kind: $kind
        inbox: $inbox
    ) {
        ...ItemPreview
        ...ItemDetail
    }
}

query SearchItem($query: String!, $kind: String!) {
    search(q: $query, kind: $kind) {
        id
        title
        author
        type
    }
}
