fragment ItemPreview on Item {
    id
    imageUrl
    title
    author
    type
    isArchived
    position
    createdAt
}

fragment ItemDetail on Item {
    productUrl
    provider
    meta
    comment
    description
}

fragment CollectionBasic on Collection {
    id
    slug
    name
    detail
}

fragment UserBasic on User {
    id
    slug
    firstname
    pictureUrl
    biography
    label
}

fragment Social on User {
    mail
    linkedin
    youtube
    website
    github
}
