query getSettings($authUserId: String!) {
    user(where: { authUserId: $authUserId }) {
        ...UserBasic
    }
}

mutation updateAvatar($authUserId: String!, $pictureUrl: String!) {
    updateOneUser(
        data: { pictureUrl: $pictureUrl }
        where: { authUserId: $authUserId }
    ) {
        ...UserBasic
    }
}

mutation updateSettings(
    $authUserId: String!
    $slug: String!
    $biography: String!
    $firstname: String!
) {
    updateOneUser(
        data: { slug: $slug, biography: $biography, firstname: $firstname }
        where: { authUserId: $authUserId }
    ) {
        ...UserBasic
    }
}

query checkUserSlug($slug: String!) {
    user(where: { slug: $slug }) {
        id
        slug
    }
}
mutation signS3($fileName: String!, $fileType: String!) {
    signS3(fileName: $fileName, fileType: $fileType) {
        signedRequest
        url
    }
}
