mutation deleteItem($id: ID!) {
    updateOneItem(data: { isArchived: true }, where: { id: $id }) {
        ...ItemPreview
        ...ItemDetail
    }
}

mutation undeleteItem($id: ID!) {
    updateOneItem(data: { isArchived: false }, where: { id: $id }) {
        ...ItemPreview
        ...ItemDetail
    }
}

mutation changePosition($oldIndex: Int!, $newIndex: Int!, $collectionId: ID!) {
    changeItemPosition(
        oldIndex: $oldIndex
        newIndex: $newIndex
        collectionId: $collectionId
    ) {
        id
        title
        position
    }
}
