query getCollectionPage($slug: String, $collectionId: String) {
    user(where: { slug: $slug }) {
        ...UserBasic
    }
    collection(where: { slug: $collectionId }) {
        ...CollectionBasic
        createdAt
        section {
            slug
        }
        items {
            id
            createdAt
            imageUrl
            comment
            productUrl
            provider
            title
            author
            type
            meta
        }
    }
}
