query getCollectionId($collectionId: ID!) {
    collection(where: { id: $collectionId }) {
        ...CollectionBasic
        createdAt
    }
}

mutation deleteCollection($id: ID!) {
    updateOneCollection(data: { isDeleted: true }, where: { id: $id }) {
        id
        slug
        isDeleted
        section {
            id
        }
    }
}

mutation unDeleteCollection($id: ID!) {
    updateOneCollection(data: { isDeleted: false }, where: { id: $id }) {
        id
        slug
        isDeleted
    }
}

mutation moveItemFromCollectionToCollection($itemId: ID!, $collectionId: ID!) {
    updateOneItem(
        data: { collection: { connect: { id: $collectionId } } }
        where: { id: $itemId }
    ) {
        id
    }
}
