query getSection($sectionId: ID!) {
    section(where: { id: $sectionId }) {
        ...SectionDetails
    }
}

mutation deleteSection($sectionId: ID!) {
    updateOneSection(data: { isDeleted: true }, where: { id: $sectionId }) {
        id
        slug
        title: name
    }
}

mutation updateSection($sectionId: ID!, $title: String) {
    updateOneSection(data: { name: $title }, where: { id: $sectionId }) {
        id
        slug
        index
        title: name
    }
}

mutation CreateEmptyCollection($sectionId: ID!) {
    collection: createEmptyCollection(sectionId: $sectionId) {
        id
        slug
        name
    }
}
